#!/bin/bash
# Test script for property dialog functionality on imported canvases
# Tests both KEGG and SBML import paths after state initialization fix

echo "========================================================"
echo "IMPORTED CANVAS PROPERTY DIALOG TEST"
echo "========================================================"
echo ""
echo "This test verifies that property dialogs work correctly on"
echo "automatically imported canvases (KEGG/SBML) after adding"
echo "mark_clean() and set_filepath() calls to match file load path."
echo ""
echo "========================================================"
echo "FIXES APPLIED:"
echo "========================================================"
echo ""
echo "✅ KEGG Import (kegg_import_panel.py:~477):"
echo "   - Added manager.mark_clean()"
echo "   - Added manager.set_filepath(temp_path) if project exists"
echo ""
echo "✅ SBML Import (sbml_import_panel.py:~733):"
echo "   - Added manager.mark_clean()"
echo "   - Added manager.set_filepath(temp_path) if project exists"
echo ""
echo "These changes match the working file load path exactly."
echo ""
echo "========================================================"
echo "TEST PROCEDURE:"
echo "========================================================"
echo ""
echo "TEST 1: KEGG Import + Property Dialog"
echo "--------------------------------------"
echo "1. Launch application: python3 src/shypn.py"
echo "2. Create or open a project (required for filepath)"
echo "3. Go to Pathways panel → Import tab"
echo "4. Enter pathway ID: hsa00010 (glycolysis)"
echo "5. Click 'Fetch'"
echo "6. Click 'Import to Canvas'"
echo "7. Right-click any TRANSITION on the imported canvas"
echo "8. Select 'Properties' from context menu"
echo ""
echo "EXPECTED: Dialog opens without Wayland Error 71 ✓"
echo "PREVIOUS: Dialog crashed with Error 71 ✗"
echo ""
echo "--------------------------------------"
echo ""
echo "TEST 2: SBML Import + Property Dialog"
echo "--------------------------------------"
echo "1. Go to Pathways panel → SBML tab"
echo "2. Enter BioModels ID: BIOMD0000000001"
echo "3. Click 'Fetch'"
echo "4. Click 'Parse' (wait for completion)"
echo "5. Click 'Load to Canvas'"
echo "6. Right-click any TRANSITION on the imported canvas"
echo "7. Select 'Properties' from context menu"
echo ""
echo "EXPECTED: Dialog opens without Wayland Error 71 ✓"
echo "PREVIOUS: Dialog crashed with Error 71 ✗"
echo ""
echo "--------------------------------------"
echo ""
echo "TEST 3: Compare with File Load (Control)"
echo "-----------------------------------------"
echo "1. File → Open → Select existing .shy file"
echo "2. Right-click any TRANSITION"
echo "3. Select 'Properties'"
echo ""
echo "EXPECTED: Dialog opens (this always worked) ✓"
echo ""
echo "========================================================"
echo "WHAT TO LOOK FOR:"
echo "========================================================"
echo ""
echo "✅ SUCCESS INDICATORS:"
echo "   - Property dialog opens smoothly"
echo "   - All dialog fields are populated"
echo "   - No Wayland Error 71 messages"
echo "   - Can edit properties and click OK"
echo "   - Canvas updates after dialog closes"
echo ""
echo "❌ FAILURE INDICATORS:"
echo "   - 'Gdk-Message: Error 71 (Protocol error)' in terminal"
echo "   - Dialog doesn't appear"
echo "   - Application freezes or crashes"
echo "   - Dialog appears but fields are empty/broken"
echo ""
echo "========================================================"
echo "DEBUG LOGGING:"
echo "========================================================"
echo ""
echo "Watch for these new log messages:"
echo ""
echo "KEGG Import:"
echo "  [KEGG_IMPORT] Canvas state initialized (marked clean)"
echo "  [KEGG_IMPORT] Canvas filepath set: /path/to/pathway.shy"
echo ""
echo "SBML Import:"
echo "  [SBML_IMPORT] Canvas state initialized (marked clean)"
echo "  [SBML_IMPORT] Canvas filepath set: /path/to/pathway.shy"
echo ""
echo "========================================================"
echo "TECHNICAL DETAILS:"
echo "========================================================"
echo ""
echo "Root Cause:"
echo "  Imported canvases had incomplete state initialization:"
echo "  - filepath = None (never set)"
echo "  - mark_clean() never called"
echo ""
echo "  This caused property dialog parent window validation to"
echo "  fail on Wayland, triggering Error 71."
echo ""
echo "Fix:"
echo "  Match the file load path by calling:"
echo "  1. manager.mark_clean() - marks canvas as clean"
echo "  2. manager.set_filepath(temp_path) - sets proper filepath"
echo ""
echo "  This ensures imported canvases have the same state"
echo "  initialization as file-loaded canvases (which work)."
echo ""
echo "========================================================"
echo ""
echo "Press Enter to launch application and begin testing..."
read

# Kill any existing instances
pkill -f "python.*shypn" 2>/dev/null
sleep 1

# Launch application
cd /home/simao/projetos/shypn
python3 src/shypn.py 2>&1 | tee test_import_dialogs.log
