#!/usr/bin/env python3
"""Test unified import buttons for KEGG and SBML."""

print("=" * 60)
print("UNIFIED IMPORT BUTTON TEST")
print("=" * 60)
print()

print("Changes Made:")
print()
print("1. KEGG Import Panel:")
print("   - Button ID fixed: 'import_button' → 'kegg_import_button'")
print("   - Unified flow: Click 'Import to Canvas' once")
print("   - If pathway not fetched: Auto-fetch first, then import")
print("   - If pathway already fetched: Go straight to import")
print()
print("2. SBML Import Panel:")
print("   - Button re-enabled: 'sbml_import_button'")
print("   - Unified flow: Click 'Import to Canvas' once")
print("   - If file not selected: Prompt to browse/enter BioModels ID")
print("   - If file selected: Parse and auto-load to canvas")
print()

print("=" * 60)
print("MANUAL TEST STEPS")
print("=" * 60)
print()

print("TEST 1: KEGG Import")
print("-" * 40)
print("1. Launch: python3 src/shypn.py")
print("2. Click 'Pathways' button (Master Palette)")
print("3. Enter pathway ID: hsa00010")
print("4. Click 'Import to Canvas' button")
print("5. Watch status: Should show:")
print("   - 🔄 Fetching pathway hsa00010 from KEGG...")
print("   - ✅ Fetched hsa00010, now importing...")
print("   - 🔄 Converting pathway to Petri net...")
print("   - ✅ Pathway imported: X places, Y transitions, Z arcs")
print("6. Check canvas: New tab should appear with pathway")
print()
print("✅ EXPECTED: One-click import from pathway ID")
print("❌ FAILURE: Button doesn't work or errors shown")
print()

print("TEST 2: SBML Import (Local File)")
print("-" * 40)
print("1. Click 'SBML' tab")
print("2. Click 'Import to Canvas' button")
print("3. Should see: File chooser dialog opens")
print("4. Select an SBML file")
print("5. Click import again")
print("6. Watch status: Should show:")
print("   - 🔄 Parsing filename.sbml...")
print("   - ✅ Parsed and validated successfully")
print("   - 🔄 Loading to canvas...")
print("   - ✅ Loaded to canvas")
print("7. Check canvas: New tab should appear with pathway")
print()
print("✅ EXPECTED: Browse, then import to canvas")
print("❌ FAILURE: Button doesn't work or errors shown")
print()

print("TEST 3: SBML Import (BioModels)")
print("-" * 40)
print("1. Select 'BioModels' radio button")
print("2. Enter model ID: BIOMD0000000010")
print("3. Click 'Import to Canvas' button")
print("4. Watch status: Should show:")
print("   - Fetching BIOMD0000000010 from BioModels...")
print("   - ✅ Fetched and saved to temp file")
print("   - 🔄 Parsing...")
print("   - ✅ Parsed and validated")
print("   - 🔄 Loading to canvas...")
print("   - ✅ Loaded to canvas")
print("5. Check canvas: New tab should appear")
print()
print("✅ EXPECTED: One-click fetch and import")
print("❌ FAILURE: Button doesn't work or errors shown")
print()

print("=" * 60)
print("KEY IMPROVEMENTS")
print("=" * 60)
print()
print("✓ Single button for complete import flow")
print("✓ No need to click Fetch, then Import separately")
print("✓ Better UX - one action does everything")
print("✓ Status messages show progress through stages")
print("✓ All operations still run in background threads")
print()

print("=" * 60)
print("Ready to test! Launch the application now.")
print("=" * 60)
