#!/usr/bin/env python3
"""
Example: Analyze Bistability Batch Results from SHYpn UI

This script demonstrates how to load batch results generated by SHYpn's
Batch Mode and create custom publication figures.

IMPORTANT: Run experiments in your working directory to preserve paper results!

Usage:
    python analyze_batch_bistability.py path/to/batch_results
    
Example:
    # From project root
    python workspace/projects/Biochemical-Examples/22_Lambda_Phage_Switch/analyze_batch_bistability.py \
           workspace/projects/My_Project/simulations/results/batch_20251213_215254
"""

import sys
import json
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path


def load_batch_results(batch_dir):
    """Load all CSV files from a batch directory"""
    batch_path = Path(batch_dir)
    
    # Load configuration
    with open(batch_path / 'config.json') as f:
        config = json.load(f)
    
    print(f"Configuration:")
    print(f"  Replicates: {config.get('replicates', 'N/A')}")
    print(f"  Recorded objects: {config.get('recorded_objects', [])}")
    print(f"  Duration: {config.get('simulation_params', {}).get('duration', 'N/A')}")
    
    # Load all trajectories
    trajectories = []
    csv_files = sorted(batch_path.glob('run_*.csv'))
    
    for csv_file in csv_files:
        with open(csv_file) as f:
            reader = csv.DictReader(f)
            data = list(reader)
            # Convert to numeric
            trajectory = {
                'time': [float(row['time']) for row in data],
            }
            # Add all recorded objects
            for key in data[0].keys():
                if key != 'time':
                    trajectory[key] = [float(row[key]) for row in data]
            trajectories.append(trajectory)
    
    print(f"\nLoaded {len(trajectories)} trajectories")
    print(f"Available objects: {list(trajectories[0].keys())}")
    
    return trajectories, config


def classify_bistability_outcomes(trajectories):
    """Classify each trajectory as lysogenic or lytic based on final PROTEIN levels
    
    CRITICAL: Use CI_Dimer (P7) and Cro_Dimer (P8), NOT state markers!
    State markers (P9, P10) are transitions/indicators, not the actual protein levels.
    
    Classification:
    - Lysogenic: CI_Dimer > 5 (high CI repressor)
    - Lytic: Cro_Dimer > 5 (high Cro)
    - Undecided: Both < 5 or both > 5
    """
    lysogenic_count = 0
    lytic_count = 0
    undecided_count = 0
    
    lysogenic_traj = []
    lytic_traj = []
    
    # Use PROTEIN DIMERS, not state markers!
    for traj in trajectories:
        ci_key = 'CI_Dimer' if 'CI_Dimer' in traj else 'P7'
        cro_key = 'Cro_Dimer' if 'Cro_Dimer' in traj else 'P8'
        
        ci_final = traj[ci_key][-1]
        cro_final = traj[cro_key][-1]
        
        if ci_final > 5 and cro_final < 5:
            lysogenic_count += 1
            lysogenic_traj.append(traj)
        elif cro_final > 5 and ci_final < 5:
            lytic_count += 1
            lytic_traj.append(traj)
        else:
            undecided_count += 1
    
    total = len(trajectories)
    print(f"\n=== Bistability Analysis ===")
    print(f"Lysogenic: {lysogenic_count}/{total} ({100*lysogenic_count/total:.1f}%)")
    print(f"Lytic:     {lytic_count}/{total} ({100*lytic_count/total:.1f}%)")
    print(f"Undecided: {undecided_count}/{total} ({100*undecided_count/total:.1f}%)")
    print(f"\nExpected (Arkin 1998): ~50% lysogenic, ~50% lytic")
    
    return lysogenic_traj, lytic_traj


def plot_bistability_figure(trajectories, lysogenic_traj, lytic_traj, output_dir):
    """Generate a 4-panel bistability figure using pandas plotting
    
    Note: Checks for both place names and IDs for compatibility:
    - CI_Dimer or P7
    - Cro_Dimer or P8
    """
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    
    # Determine which keys to use (name or ID)
    ci_key = 'CI_Dimer' if 'CI_Dimer' in trajectories[0] else 'P7'
    cro_key = 'Cro_Dimer' if 'Cro_Dimer' in trajectories[0] else 'P8'
    
    # Panel A: Stochastic Trajectories (SUBSET + PAPER-STYLE RESOLUTION)
    ax1 = axes[0, 0]
    if ci_key in trajectories[0] and cro_key in trajectories[0]:
        # Show only subset with ~200 points (paper resolution)
        max_trajectories = 10
        target_points = 200  # Paper uses ~200 points for clean appearance
        
        # Plot subset of lysogenic trajectories (CI)
        for traj in lysogenic_traj[:max_trajectories]:
            df = pd.DataFrame({'time': traj['time'], 'CI': traj[ci_key]})
            # Resample to paper resolution
            step = max(1, len(df) // target_points)
            df_resampled = df.iloc[::step]
            df_resampled.plot(x='time', y='CI', ax=ax1, color='blue', alpha=0.3, 
                   linewidth=0.5, legend=False)
        
        # Plot subset of lytic trajectories (Cro)
        for traj in lytic_traj[:max_trajectories]:
            df = pd.DataFrame({'time': traj['time'], 'Cro': traj[cro_key]})
            step = max(1, len(df) // target_points)
            df_resampled = df.iloc[::step]
            df_resampled.plot(x='time', y='Cro', ax=ax1, color='red', alpha=0.3, 
                   linewidth=0.5, legend=False)
        
        ax1.set_xlabel('Time (simulation units)')
        ax1.set_ylabel('Protein Dimer concentration')
        ax1.set_title('(A) Stochastic Trajectories (20 representative runs)')
        ax1.legend([plt.Line2D([0], [0], color='blue', alpha=0.8, linewidth=2),
                    plt.Line2D([0], [0], color='red', alpha=0.8, linewidth=2)],
                   ['Lysogenic (CI high)', 'Lytic (Cro high)'])
        ax1.grid(True, alpha=0.3)
    
    # Panel B: Outcome percentages
    ax2 = axes[0, 1]
    lysogenic_pct = 100 * len(lysogenic_traj) / len(trajectories)
    lytic_pct = 100 * len(lytic_traj) / len(trajectories)
    
    categories = ['Model\nLysogenic', 'Expected\nLysogenic', 'Model\nLytic', 'Expected\nLytic']
    values = [lysogenic_pct, 50, lytic_pct, 50]
    colors = ['blue', 'lightblue', 'red', 'lightcoral']
    
    bars = ax2.bar(categories, values, color=colors)
    ax2.set_ylabel('Percentage (%)')
    ax2.set_title('(B) Decision Statistics')
    ax2.set_ylim([0, 100])
    ax2.axhline(y=50, color='gray', linestyle='--', alpha=0.5)
    for bar, val in zip(bars, values):
        height = bar.get_height()
        ax2.text(bar.get_x() + bar.get_width()/2., height,
                f'{val:.1f}%', ha='center', va='bottom')
    ax2.grid(True, alpha=0.3, axis='y')
    
    # Panel C: Phase Portrait (SUBSET + first 50 units + PAPER RESOLUTION)
    ax3 = axes[1, 0]
    if ci_key in trajectories[0] and cro_key in trajectories[0]:
        # Show only SUBSET with paper-style resolution (~50 points for first 50 units)
        max_trajectories = 10
        time_cutoff = 50
        target_points = 50  # ~1 point per time unit
        
        for traj in lysogenic_traj[:max_trajectories]:
            # Filter to first 50 time units
            mask = np.array(traj['time']) <= time_cutoff
            df = pd.DataFrame({
                'CI': np.array(traj[ci_key])[mask],
                'Cro': np.array(traj[cro_key])[mask]
            })
            # Resample to paper resolution
            step = max(1, len(df) // target_points)
            df_resampled = df.iloc[::step]
            df_resampled.plot(x='CI', y='Cro', ax=ax3, color='blue', alpha=0.3, 
                       linewidth=0.5, legend=False)
            # Mark final state
            if len(df_resampled) > 0:
                ax3.plot(df_resampled['CI'].iloc[-1], df_resampled['Cro'].iloc[-1], 'o', 
                        color='blue', markersize=5, alpha=0.7)
        
        for traj in lytic_traj[:max_trajectories]:
            mask = np.array(traj['time']) <= time_cutoff
            df = pd.DataFrame({
                'CI': np.array(traj[ci_key])[mask],
                'Cro': np.array(traj[cro_key])[mask]
            })
            step = max(1, len(df) // target_points)
            df_resampled = df.iloc[::step]
            df_resampled.plot(x='CI', y='Cro', ax=ax3, color='red', alpha=0.3, 
                       linewidth=0.5, legend=False)
            if len(df_resampled) > 0:
                ax3.plot(df_resampled['CI'].iloc[-1], df_resampled['Cro'].iloc[-1], 'o', 
                        color='red', markersize=5, alpha=0.7)
        
        ax3.set_xlabel('CI Dimer concentration')
        ax3.set_ylabel('Cro Dimer concentration')
        ax3.set_title('(C) Phase Portrait (20 runs, first 50 time units)')
        ax3.legend([plt.Line2D([0], [0], marker='o', color='w', markerfacecolor='blue', markersize=8),
                    plt.Line2D([0], [0], marker='o', color='w', markerfacecolor='red', markersize=8)],
                   ['Lysogenic', 'Lytic'])
        ax3.grid(True, alpha=0.3)
    
    # Panel D: Final state distributions
    ax4 = axes[1, 1]
    if ci_key in trajectories[0]:
        final_ci = [traj[ci_key][-1] for traj in trajectories]
        ax4.hist(final_ci, bins=20, color='purple', alpha=0.7, edgecolor='black')
        ax4.axvline(x=np.mean(final_ci), color='red', linestyle='--', linewidth=2,
                    label=f'Mean: {np.mean(final_ci):.2f}')
        ax4.set_xlabel('Final CI Dimer Level')
        ax4.set_ylabel('Frequency')
        ax4.set_title('(D) Final State Distribution')
        ax4.legend()
        ax4.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    # Save figure
    output_path = Path(output_dir) / 'figure2_bistability_validation.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"\n✓ Figure saved: {output_path}")
    plt.show()


def main():
    if len(sys.argv) < 2:
        print("Usage: python analyze_batch_bistability.py <batch_directory>")
        print("\nExample (from project root):")
        print("  python workspace/projects/Biochemical-Examples/22_Lambda_Phage_Switch/analyze_batch_bistability.py \\")
        print("         workspace/projects/My_Project/simulations/results/batch_20251213_215254")
        sys.exit(1)
    
    batch_dir = sys.argv[1]
    
    if not Path(batch_dir).exists():
        print(f"Error: Directory not found: {batch_dir}")
        sys.exit(1)
    
    print("=" * 70)
    print("Lambda Phage Bistability Analysis")
    print("Using Real SHYpn Batch Mode Results")
    print("=" * 70)
    print(f"\nBatch directory: {batch_dir}\n")
    
    # Load results
    trajectories, config = load_batch_results(batch_dir)
    
    # Classify outcomes
    lysogenic_traj, lytic_traj = classify_bistability_outcomes(trajectories)
    
    # Generate figure - save to working directory results
    output_dir = Path(batch_dir).parent
    output_dir.mkdir(exist_ok=True, parents=True)
    plot_bistability_figure(trajectories, lysogenic_traj, lytic_traj, output_dir)
    
    print("\n" + "=" * 70)
    print("Analysis complete!")
    print("=" * 70)


if __name__ == "__main__":
    main()
